### ISSUE TITLE
iOS 15 on iPhone 7 - NfcError of Security violation

### ISSUE THREAD

**Issue by gcantara** [revtel/react-native-nfc-manager#611]
Hi,
I developed and published an Android application, where NfcManager works perfectly for my behaviors.

Now I have to do same things with iOs system.

I have enabled "expo-dev-client" to deploy my app on the device.
I'm able to call NfcManager.start() without issues.

I modified the .plist and the .entitlements files like said on https://github.com/hansemannn/iOS11-NFC-Example and my app can be installed after that.

But when I call "await NfcManager.requestTechnology(NfcTech.Ndef)" the application got an error:
at node_modules/react-native-nfc-manager/src/NfcError.js:1:38 in <global>
at node_modules/react-native-nfc-manager/src/NfcError.js:3:25 in NfcErrorBase
at node_modules/react-native-nfc-manager/src/NfcError.js:1:38 in <global>
at node_modules/react-native-nfc-manager/src/NfcError.js:5:30 in SecurityViolation
at node_modules/react-native-nfc-manager/src/NfcError.js:91:36 in buildNfcExceptionIOS
at node_modules/react-native-nfc-manager/src/NfcError.js:156:36 in handleNativeException

What I'm still wrong? Where can I have take a look?

Many thanks for Help.

Gianfranco

**Comment by gcantara** [comment]
I solved my issue.

I was on the plist file, I added those lines:
    <key>NFCReaderUsageDescription</key>
    <string>We need to use NFC</string>
    <key>com.apple.developer.nfc.readersession.formats</key>
	  <array>
		  <string>TAG</string>
	  </array>
    <key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
    <array>
      <string>D2760000850100</string>
      <string>D2760000850101</string>
    </array>

and in the entitlements:
	<key>com.apple.developer.nfc.readersession.formats</key>
	<array>
		<string>TAG</string>
		<string>NDEF</string>
	</array>

Regards.
